mytr={
    'az_tarikh':'از تاریخ',
    'ta_tarikh':'تا تاریخ',
    'chehreh':'چهره',
    'pelak':'پلاک',
    'person':'افراد',
    'videos':'ویدئوها',
    'search':'جستجو',
    'az_saat':'از ساعت',
    'moshahede':'مشاهده',
    'radif':'ردیف',
    'tarikh':'تاریخ',
    'saat':'ساعت',
    'tasvir':'تصویر',
    'select_soojeh':'انتخاب سوژه',
    'sabt':'ثبت',
    'sabte_karbare_jadid':'ثبت آی پی کاربر جدید',
    'hazfe_karbar_az_list':'حذف آی پی کاربر از لیست',
    'list_karbaran':'لیست آی پی کاربران',
    'back':'بازگشت',
    'key':'کلید رمزنگاری',
    'sender_ip':'آی پی فرستنده',
    'center_ip':'آی پی مرکز فرماندهی',
    'quality_frame':'کیفیت ارسال تصاویر',
    'url_cam1':'آدرس دوربین اول',
    'url_cam2':'آدرس دوربین دوم',
    'url_cam3':'آدرس دوربین سوم',
    'url_cam4':'آدرس دوربین چهارم',
    'count_frame_detect':'تعداد فریم های تشخیص از 30 فریم',
    'save_videos':'ذخیره ویدئوها',
    'update':'به روزرسانی',
    'warning':'اخطار',
    'for_delete_select_ip_before':'برای حذف ابتدا باید آی پی را انتخاب کنید',
    'select_soojeh_first':'لطفا نام سوژه را انتخاب نمایید',
    'before_any_connection_select_soojeh_name':'قبل از شروع حتما باید از قسمت تنظیمات نام سوژه را ثبت کنید',
    'general_setting':'تنظیمات عمومی',
    'view_camera_setting':'تنظیمات دوربین ها',

}